export const ROUTES = {
  LANDING: "/",
  HOME: "/home",
  LOGIN: "/auth/login",
  SIGNUP: "/auth/signup",
  DASHBOARD: "/dashboard",
  INQUIRIES: "/inquiries",
  NEW_INQUIRIES: "/inquiries/new",
  PROPOSALS: "/proposals",
  CONTRACTS: "/contracts",
  DELIVERIES: "/deliveries",
  INVOICES: "/invoices",
  RUNNING_ORDERS: "/running-orders",
  PAYMENTS: "/payments",
  TAX_CHALLANS: "/tax-challans",
  CLIENTS: "/clients",
  HIRE_AGENT: "/hire-agent",
  ANALYTICS: "/analytics",
  SUPPLY_CHAIN: "/supply-chain",
  USER_MANAGEMENT: "/user-management",
  CHOOSE_ROLE: "/auth/choose-role",
  PROFILE_SETUP: "/auth/profile-setup",
  COMPLETE_PROFILE: "/auth/complete-profile",
  SETTINGS: "/settings",
  NOT_FOUND: "/404",
};
